FROM centos
MAINTAINER Anurag
COPY httpd_script.sh /tmp/
#COPY https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz  /tmp/
#Gives Syntax error for above line as COPY cannot do untar/unzip and remote URL handling
ADD testfile  /tmp/
ADD https://download.mobatek.net/2102021022292334/MobaXterm_Portable_v21.0.zip  /tmp/
